name:                practica-minigolfito
version:             0.1.0.0
github:              "pdepjm/practica-minigolfito"
license:             BSD3
author:              "PdeP JM"
maintainer:          "pdepjm@googlegroups.com"
copyright:           "2020 PdeP JM"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/pdepjm/practica-minigolfito#readme>

dependencies:
- base >= 4.7 && < 5
- pdeprelude

default-extensions:
  - NoImplicitPrelude
  - FlexibleContexts
  - RebindableSyntax

library:
  source-dirs: src
  other-modules: []
